name: lethean
base: core18
adopt-info: lethean
summary: "Lethean: official wallet. Secure. Scalable. Easy to Use."
description: "Lethean is a user psecurity project, utlizing a scalable e-commerce friendly confidential blockchain."
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  lethean:
    source: https://github.com/letheanVPN/blockchain-iTw3.git
    plugin: cmake
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version "$(git describe)"
    configflags:
      - -DBUILD_GUI=TRUE
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/Lethean
      cp $SNAPCRAFT_PART_BUILD/src/Lethean $SNAPCRAFT_PART_INSTALL/opt/Lethean/
      cp $SNAPCRAFT_PART_BUILD/src/simplewallet $SNAPCRAFT_PART_INSTALL/opt/Lethean/
      cp $SNAPCRAFT_PART_BUILD/src/letheand $SNAPCRAFT_PART_INSTALL/opt/Lethean/
      rsync -a $SNAPCRAFT_PART_SRC/src/gui/qt-daemon/html $SNAPCRAFT_PART_INSTALL/opt/Lethean --exclude less --exclude package.json --exclude gulpfile.js
    build-packages:
      - make
      - g++
      - libboost-all-dev
      - qtwebengine5-dev
      - rsync
    build-attributes: [keep-execstack]
    stage-packages:
      - libboost-system1.65.1
      - libboost-filesystem1.65.1
      - libboost-thread1.65.1
      - libboost-date-time1.65.1
      - libboost-chrono1.65.1
      - libboost-regex1.65.1
      - libboost-serialization1.65.1
      - libboost-program-options1.65.1
      - libboost-locale1.65.1

apps:
  lethean:
    command: opt/Lethean/Lethean --data-dir $SNAP_USER_COMMON
    extensions:
      - kde-neon
    plugs:
      - network
      - home
      - desktop
      - opengl #for QML support
      - browser-support #for Qt WebEngine support
      - audio-playback
      - unity7 #for tray icon support
  simplewallet:
    command: opt/Lethean/simplewallet
    plugs:
      - network
      - home
  letheand:
    command: opt/Lethean/letheand --data-dir $SNAP_USER_COMMON
    environment:
      LC_ALL: C
    plugs:
      - network
      - network-bind
