name: Build - Linux

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ubuntu:
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Eat the Choco
        run: |
          choco install boost-msvc-14.2 --version 1.74.0 -y
          choco install qt5-default --version 5.15.2.20211228 -y
          choco install cmake --version 3.23.1 -y 
          choco install openssl --version 1.1.1.1500 -y
      - name: install dependencies
        run: sudo apt-get install -y build-essential g++ python-dev autotools-dev libboost-all-dev libssl-dev libicu-dev libbz2-dev cmake git screen checkinstall zlib1g-dev
      - name: build server
        env:
          QT_PREFIX_PATH: C:\dev\_sdk\Qt5.11.2\5.11.2
          INNOSETUP_PATH: C:\Program Files (x86)\Inno Setup 5\ISCC.exe
          ETC_BINARIES_PATH: C:\dev\deploy\etc-binaries
          BUILDS_PATH: C:\dev\deploy\zano
          LOCAL_BOOST_PATH: C:\dev\_sdk\boost_1_70_0
          OPENSSL_ROOT_DIR: C:\dev\_sdk\OpenSSL-Win64
          BOOST_ROOT: %LOCAL_BOOST_PATH%
        run: |
          mkdir build && cd build
          cmake -D STATIC=true -D ARCH=x86-64 -D TESTNET=TRUE -D CMAKE_BUILD_TYPE=Release ..
          make -j2 daemon simplewallet
      - name: Tar files
        run: cd build/src && tar -cvf ../../server-linux-amd64.tar letheand simplewallet
      - uses: actions/upload-artifact@v3
        with:
          name: server-linux-amd64
          if-no-files-found: error
          path: server-linux-amd64.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          files: ${{ github.workspace }}/server-linux-amd64.tar