name: Build - MacOS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: install dependencies
        run: brew install openssl boost icu4c
      - name: build server
        env:
          PKG_CONFIG_PATH: "/usr/local/opt/openssl@3/lib/pkgconfig"
        run: |
          export LIBRARY_PATH=${LIBRARY_PATH}:/usr/local/opt/icu4c/lib
          make static-release-testnet
      - name: Tar files
        run: cd build/src && tar -cvf ../../testnet-server-macos-amd64.tar letheand simplewallet
      - uses: actions/upload-artifact@v3
        with:
          name: testnet-server-macos-amd64
          if-no-files-found: error
          path: testnet-server-macos-amd64.tar
