name: Build - Linux

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: update apt
        run: sudo apt update & sudo apt-get upgrade -y
      - name: install dependencies
        run: sudo apt-get install -y python-dev autotools-dev libboost-all-dev libicu-dev libbz2-dev git screen checkinstall zlib1g-dev
      - name: build server
        run: make static-release-testnet
      - name: Tar files
        run: cd build/src && tar -cvf ../../testnet-server-linux-amd64.tar letheand simplewallet
      - uses: actions/upload-artifact@v3
        with:
          name: testnet-server-linux-amd64
          if-no-files-found: error
          path: testnet-server-linux-amd64.tar
