name: cli-testnet

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  HUNTER_CACHE_TOKEN: ${{ secrets.HUNTER_CACHE_TOKEN }}
  CCACHE_SETTINGS: |
    ccache --max-size=150M
    ccache --set-config=compression=true

jobs:
  linux-amd64:
    runs-on: ubuntu-20.04
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Process Hunter Cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.hunter
          key: hunter-${{ runner.os }}
          restore-keys: hunter-${{ runner.os }}
      - name: Process Ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-build-testnet-cli
          restore-keys: ccache-${{ runner.os }}-build-testnet-cli
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: |
          sudo apt-get install -y python-dev autotools-dev libbz2-dev git screen checkinstall zlib1g-dev ccache miniupnpc
          pip install gitpython requests
      - name: build server
        run: |
          ${{env.CCACHE_SETTINGS}}
          ./utils/build/testnet_linux_cli.sh
      - uses: actions/upload-artifact@v3
        with:
          name: lethean-linux-cli
          if-no-files-found: error
          path: lethean-linux-cli-*.tar.bz2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/lethean-linux-cli-*.tar.bz2
  macos-amd64:
    runs-on: macos-latest
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Process Hunter Cache
        uses: actions/cache@v3
        with:
          path: /Users/runner/.hunter
          key: hunter-${{ runner.os }}
          restore-keys: hunter-${{ runner.os }}
      - name: Process ccache
        uses: actions/cache@v3
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ccache-${{ runner.os }}-build-testnet-cli
          restore-keys: ccache-${{ runner.os }}-build-testnet-cli
      - name: hacky python fix
        run: |
          cd /usr/local/Frameworks/Python.framework/Versions/3.11/bin/
          ./pip3 install requests gitpython
      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache miniupnpc
      - name: build server
        run: |
          ${{env.CCACHE_SETTINGS}}
          ./utils/build/testnet_mac_osx_cli.sh
      - uses: actions/upload-artifact@v3
        with:
          name: lethean-macos-cli
          if-no-files-found: error
          path: lethean-macos-cli-*.tar.bz2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/lethean-macos-cli-*.tar.bz2
  windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: ~\.ccache
          key: ccache-${{ runner.os }}-build-testnet-cli
          restore-keys: ccache-${{ runner.os }}-build-testnet-cli
      - name: Eat the Choco
        run: |
          choco install ccache -y
          choco install zip -y
      - name: hacky python fix
        shell: cmd
        working-directory: C:/hostedtoolcache/windows/Python/3.11.1/x86/
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o C:/hostedtoolcache/windows/Python/3.11.1/x86/get-pip.py
          C:/hostedtoolcache/windows/Python/3.11.1/x86/python C:/hostedtoolcache/windows/Python/3.11.1/x86/get-pip.py
          C:/hostedtoolcache/windows/Python/3.11.1/x86/Scripts/pip.exe install requests gitpython
      - name: build server
        env:
          QT_PREFIX_PATH: C:\ProgramData\chocolatey\lib\Qt5.11.2\5.11.2
        run: |
          ${{env.CCACHE_SETTINGS}}
          ./utils/build/testnet_windows_cli.bat
      - uses: actions/upload-artifact@v3
        with:
          name: lethean-windows-cli
          if-no-files-found: error
          path: ${{ github.workspace }}\lethean-win-cli-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/lethean-win-cli-*.zip
  windows-amd642:
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: ~\.ccache
          key: ccache-${{ runner.os }}-build-testnet-cli
          restore-keys: ccache-${{ runner.os }}-build-testnet-cli
      - name: Eat the Choco
        run: |
          choco install ccache -y
          choco install zip -y
      - name: hacky python fix
        run: |
          pip install requests gitpython
      - name: build server
        env:
          QT_PREFIX_PATH: C:\ProgramData\chocolatey\lib\Qt5.11.2\5.11.2
        run: |
          ${{env.CCACHE_SETTINGS}}
          ./utils/build/testnet_windows_cli.bat
      - uses: actions/upload-artifact@v3
        with:
          name: lethean-windows-cli
          if-no-files-found: error
          path: ${{ github.workspace }}\lethean-win-cli-*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/lethean-win-cli-*.zip
