name: chain-itw3:testnet
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Log in to registry
        if: startsWith(github.ref, 'refs/head/')
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: utils/docker/Dockerfile
          push: true
          tags: lthn/chain-itw3:testnet
      - name: Build and push
        if: startsWith(github.ref, 'refs/head/')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: utils/docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chain-itw3:testnet
