name: gui-testnet

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CCACHE_SETTINGS: |
    ccache --max-size=150M
    ccache --set-config=compression=true

jobs:
  macos-amd64:
    runs-on: macos-latest
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ccache-${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ccache-${{ runner.os }}-build-
      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl boost icu4c ccache miniupnpc qt@5
      - name: build server
        env:
          PKG_CONFIG_PATH: "/usr/local/opt/openssl@3/lib/pkgconfig"
        run: |
          ${{env.CCACHE_SETTINGS}}
          export LIBRARY_PATH=${LIBRARY_PATH}:/usr/local/opt/icu4c/lib
          make gui-release-testnet -j3
      - name: Tar files
        run: cd build/release/src/gui && tar -cvf ../../../testnet-desktop-macos-amd64.tar Lethean.app
      - uses: actions/upload-artifact@v3
        with:
          name: testnet-desktop-macos-amd64
          if-no-files-found: error
          path: testnet-desktop-macos-amd64.tar
