name: Linux

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: update apt
        run: sudo apt update & sudo apt-get upgrade -y
      - name: install dependencies
        run: sudo apt-get install -y build-essential g++ python-dev autotools-dev libicu-dev libbz2-dev cmake git screen checkinstall zlib1g-dev
      - run: |
          curl -OL https://boostorg.jfrog.io/artifactory/main/release/1.70.0/source/boost_1_70_0.tar.bz2
          tar -xjf boost_1_70_0.tar.bz2
          cd boost_1_70_0
          ./bootstrap.sh --with-libraries=system,filesystem,thread,date_time,chrono,regex,serialization,atomic,program_options,locale,timer,log
          ./b2 install
      - name: build server
        run: bash utils/build_script_linux.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/build/release