name: Linux

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: update apt
        run: sudo apt update & apt-get upgrade -y
      - name: install dependencies
        run: sudo apt-get install -y build-essential libboost-all-dev g++ python-dev autotools-dev libicu-dev libbz2-dev cmake git screen mesa-common-dev libglu1-mesa-dev
      - name: build server
        run: make -j2
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/build/