name: Server - Linux

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: update apt
        run: sudo apt update & sudo apt-get upgrade -y
      - name: install dependencies
        run: sudo apt-get install -y build-essential g++ python-dev autotools-dev libboost-all-dev libssl-dev libicu-dev libbz2-dev cmake git screen checkinstall zlib1g-dev
      - name: build server
        run: |
          mkdir build && cd build
          cmake -D TESTNET=TRUE ..
          make -j2 daemon simplewallet
      - name: Tar files
        run: tar -cvf server-linux-amd64.tar ${{ github.workspace }}/build/src/letheand ${{ github.workspace }}/build/src/simplewallet
      - uses: actions/upload-artifact@v3
        with:
          name: server-linux-amd64
          if-no-files-found: error
          path: server-linux-amd64.tar